[package]
name = "oppai-zero-torch"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2021"

[dependencies]
ndarray = "0.15"
num-traits = "0.2"
indoc = "2.0"
pyo3 = { version = "0.18", features = ["auto-initialize"] }
numpy = "0.18"
oppai-zero = { path = "../zero" }
