[package]
name = "oppai-zero-torch"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2021"

[dependencies]
ndarray = "0.15"
indoc = "1.0"
pyo3 = "0.17"
numpy = "0.17"
oppai-zero = { path = "../zero" }
