[package]
name = "oppai"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2021"

[dependencies]
rand = { version = "0.8", features = [ "small_rng" ] }
time = "0.3"
env_logger = "0.10"
crossbeam = "0.8"
clap = { version = "4.4", features = [ "cargo" ] }
strum = "0.25"
oppai-common = { path = "common" }
oppai-ladders = { path = "ladders" }
oppai-uct = { path = "uct" }
oppai-minimax = { path = "minimax" }
oppai-bot = { path = "bot" }

[features]
default = ["dsu"]
dsu = ["oppai-bot/dsu"]

[profile.dev]
opt-level = 0
lto = false
debug = true
panic = "unwind"

[profile.test]
opt-level = 3
lto = false
debug = true

[profile.bench]
opt-level = 3
lto = true
debug = false

[profile.release]
opt-level = 3
lto = true
debug = false
panic = "abort"
codegen-units = 1

[workspace]
members = [
  "field",
  "common",
  "rotate",
  "ladders",
  "test-images",
  "uct",
  "minimax",
  "patterns",
  "zero",
  "zero-burn",
  "zero-train",
  "bot",
  "initial",
  "iced",
  "svg",
  "sgf",
  # "versus"
]
