[package]
name = "oppai"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2018"

[dependencies]
rand = { version = "0.8", features = [ "small_rng" ] }
time = "0.3"
env_logger = "0.9"
crossbeam = "0.8"
clap = "2.33"
strum = "0.21"
oppai-field = { path = "field" }
oppai-common = { path = "common" }
oppai-ladders = { path = "ladders" }
oppai-uct = { path = "uct" }
oppai-minimax = { path = "minimax" }
oppai-patterns = { path = "patterns" }
oppai-bot = { path = "bot", features = [ "cli" ] }

[features]
default = ["dsu"]
dsu = ["oppai-field/dsu"]

[profile.dev]
opt-level = 0
lto = false
debug = true
panic = "unwind"

[profile.test]
opt-level = 3
lto = false
debug = true

[profile.bench]
opt-level = 3
lto = true
debug = false

[profile.release]
opt-level = 3
lto = true
debug = false
panic = "abort"
codegen-units = 1

[workspace]
members = [
  "field",
  "common",
  "ladders",
  "test-images",
  "uct",
  "minimax",
  "patterns",
  "zero",
  "zero-tf",
  "bot",
  "iced"
]
