[package]
name = "oppai-zero-train"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2021"

[dependencies]
ndarray = "0.15"
pyo3 = "0.18"
numpy = "0.18"
num-traits = "0.2"
rand = { version = "0.8", features = [ "small_rng" ] }
log = "0.4"
env_logger = "0.10"
clap = { version = "4.4", features = [ "cargo" ] }
anyhow = "1.0"
sgf-parse = "4.2"
oppai-field = { path = "../field" }
oppai-initial = { path = "../initial" }
oppai-sgf = { path = "../sgf" }
oppai-zero = { path = "../zero" }
oppai-zero-torch = { path = "../zero-torch" }

[dev-dependencies]
rand_xoshiro = "0.6"

[features]
default = ["dsu"]
dsu = ["oppai-field/dsu"]
