[package]
name = "oppai-zero-train"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2021"

[dependencies]
ndarray = "0.15"
num-traits = "0.2"
burn = { version = "0.12", features = ["train", "ndarray", "wgpu"] }
rand = { version = "0.8", features = [ "small_rng" ] }
rand_distr = "0.4"
log = "0.4"
env_logger = "0.11"
clap = { version = "4.4", features = [ "cargo" ] }
anyhow = "1.0"
sgf-parse = "4.2"
strum = { version = "0.26", features = [ "derive" ] }
oppai-field = { path = "../field" }
oppai-initial = { path = "../initial" }
oppai-sgf = { path = "../sgf", features = [ "zero" ] }
oppai-zero = { path = "../zero" }
oppai-zero-burn = { path = "../zero-burn" }

[dev-dependencies]
rand_xoshiro = "0.6"

[features]
default = ["dsu"]
dsu = ["oppai-field/dsu"]
