[package]
name = "oppai-zero"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2018"

[dependencies]
rand = "0.8"
ndarray = "0.15"
decorum = "0.3"
oppai-field = { path = "../field" }

[dev-dependencies]
rand_xoshiro = "0.6"
