[package]
name = "oppai-zero"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2021"

[dependencies]
rand = "0.8"
ndarray = { version = "0.15", features = ["serde"] }
num-traits = "0.2"
log = "0.4"
serde = "1.0"
oppai-field = { path = "../field" }
oppai-rotate = { path = "../rotate" }

[dev-dependencies]
rand_xoshiro = "0.6"
