[package]
name = "oppai-iced"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2018"

[dependencies]
iced = { version = "0.3", features = [ "canvas" ] }
rand = { version = "0.8", features = [ "small_rng" ] }
log = "0.4"
env_logger = "0.8"
clap = "2.33"
humantime = "2.1"
rfd = { version = "0.2", features = [ "file-handle-inner" ] }
sgf-parser = "2.6"
oppai-field = { path = "../field" }
oppai-patterns = { path = "../patterns" }
oppai-bot = { path = "../bot", features = [ "cli" ] }

[features]
default = ["dsu"]
dsu = ["oppai-field/dsu"]
